### ISSUE TITLE
bug: per mode confs doesn't activate for new -> saveas buf (simple fix)

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#330] opened 2017-03-10 19:31 UTC
- create new buf
- save as foo.md
- typing: no soft wrapping of lines take place
- cmdline -> `set line-wrap <tab>` -> shows that the settings are correct for mode+buf (set to word), and global is set to none - (_I cancel here now_).
- simply switching to another buffer within the same view and immediately switching back makes the correct settings take effect.

**Comment by nilnor** [comment] 2017-03-24 18:48
I can't reproduce this I'm afraid. After saving as markdown I still get soft wrapping. This is with running without a profile (`--no-profile`). Do you get it while running it the same way?

**Comment by ozra** [comment] 2017-03-28 21:20
- I've updated to latest head now, and now it doesn't even get the setting after switching buffer back n forth.
- With `--no-profile` it works fine.

Which seems to mean that module specific settings from init.moon doesn't get applied (?)
Here's the cut out lines from my init.conf that are related to the setting:

```moonscript
c = howl.config
c.line_wrapping = "none"
howl.mode.configure "markdown",
  line_wrapping:  "word"
```

**Comment by shalabhc** [comment] 2017-03-28 23:09
@ozra can you see if replacing the last two lines with this code works?

```moon
howl.mode.by_name('markdown').config.line_wrapping = "word"
```

**Comment by ozra** [comment] 2017-03-28 23:24
@shalabhc - changing to that line then it catches the right settings on flip-buffer like before, but still not on file save.

**Comment by shalabhc** [comment] 2017-03-29 05:06
I'm looking into this and I can reproduce this problem. I think it's a issue with how config watching and broadcast works. A related issue is in editor.moon (https://github.com/howl-editor/howl/blob/master/lib/howl/ui/editor.moon#L40) - the handler for config changes seems to update *all* editors - while it should only update the editor where the property applies.

**Comment by shalabhc** [comment] 2017-03-29 05:17
Filed #343 for the related issue. Once that is fixed, I will look into the watching/broadcast again.

**Comment by shalabhc** [comment] 2017-03-29 08:16
Also filed #347 as an offshoot of this, and have PR #345 to fix a config evaluation precedence issue.

**Comment by ozra** [comment] 2017-03-29 12:07
neat!

**Comment by shalabhc** [comment] 2017-05-28 07:02
OK, I think this should be fully fixed after #356 is merged. Feel free to try that out if you get get a chance.

**Comment by ozra** [comment] 2017-05-28 18:43
Cool. I'll try it out when I'm back home!

**Comment by ozra** [comment] 2017-05-29 22:31
Works like a charm!

**Closed** 2017-05-29 22:31 UTC
Labels: bug
