### ISSUE TITLE
Brace matching doesn't always work at EOL

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#264] opened 2016-10-03 16:27 UTC
To reproduce:

- Open a new file `x.c`.
- Paste the following:
    ```
{

}
    ```
- Hit page up to go to the top of the file.
- Hit the down arrow.
- Hit the left arrow.

**Expected result:** The two braces will be highlighted.
**Actual result:** They aren't. Oddly enough, this works if you go to the right brace using the right arrow from the first line.

**Comment by shalabhc** [comment] 2016-10-03 23:55
What do you see? Only one brace highlighted or niether?

I wasn't able to reproduce this. I do see only one brace highlighted when there is no trailing newline on the closing brace - that's already filed as another bug.

**Comment by kirbyfan64** [comment] 2016-10-04 00:22
@shalabhc Neither, and for me it doesn't work even with a trailing newline. I just accidentally forgot a kind-of important reproduction step... :O I fixed the list.

**Comment by shalabhc** [comment] 2016-10-12 18:29
OK - able to reproduce.

**Comment by shalabhc** [comment] 2016-10-12 18:39
Weird one - with some logging it seems the matching logic works fine and calls the buffer.markers\add() method - it's just that no highlight is displayed. In another case, the exact same call does display the highlight. Haven't investigated into the markers code itself.

**Comment by nilnor** [comment] 2016-10-18 10:29
Duplicate of #183.

**Closed by nilnor** 2016-10-18 10:29 UTC
Labels: bug
