### ISSUE TITLE
With vi-on and any buffer-mode, `{` inserts a `{` character if cursor is at the start of a line.

### ISSUE THREAD

**Issue by wtok** [howl-editor/howl#338] opened 2017-03-23 16:51 UTC
Steps to demonstrate:

- Use `vi-on`, and open some code file (say, `init.lua`).
- Stay in normal mode (not insert mode).
- Go anywhere, and type `}`. It goes forward a paragraph as expected.
- Navigate to the start of the line, and type `{`. It inserts a `{` character (and a matching `}` character), even though you're not in insert mode.
- Navigate *anywhere except* the start of a line, then type `{`. It works as expected.

This only seems to behave this way if Howl has picked a buffer-mode for the buffer. If you open a `.txt` file or some file Howl doesn't have a mode for, `{` works as expected anywhere.

**Comment by wtok** [comment] 2017-03-24 10:26
Addendum: When `auto_pair` is set to false, this bug doesn't occur.

**Comment by nilnor** [comment] 2017-03-24 18:27
Thanks, should be fixed now!

**Closed** 2017-03-24 18:26 UTC
Labels: bug

**Comment by wtok** [comment] 2017-03-25 06:15
I've just pulled from master and I'm getting some really weird behaviour. 

It seems I can't enter text in insert mode except for `{` characters. I'm also having some difficulty getting `vi-off` to work. When I manage to get the `-- VI --` text to disappear, Howl still acts as if it's in Vi normal mode. Pressing `i` goes to insert mode (which doesn't work), then pressing escape goes back to `-- VI --`.

Can you confirm any of this on your end?

**Comment by nilnor** [comment] 2017-03-25 06:48
Hi, no I can't reproduce this I'm afraid. Since you're new (and related to a FAQ) - did you remember to make again after pulling from master?

**Comment by wtok** [comment] 2017-03-25 06:58
I did run make again, yeah. I just deleted my Howl folder and re-cloned it and saw the issue again. The first thing in my `init.lua` file is `howl.command.vi_on()`. If I remove that line, everything works fine. If I put it back, I run into the issues above.

**Comment by nilnor** [comment] 2017-03-25 07:21
So, the issue is that one shouldn't run command directly from within the initialization file, as the application isn't fully started yet and lacks things such as a window, current editor, etc. There's a check for this when running command using `command.run(..)`, but it was lacking for the case where one invokes commands directly using `command.<my_command>`.

I added the check to the other case now as well which should avoid any confusion by raising a hopefully explanatory error. Quick snippet for your use in the init file:

```moonscript
signal.connect 'app-ready', ->
  howl.command.vi_on!
```

**Comment by wtok** [comment] 2017-03-25 08:10
Okay, cheers for clearing that up. Using `howl.signal.connect('app-ready', howl.command.vi_on)` works fine. However I might point out this misleading piece of documentation, from http://howl.io/doc/manual/configuration.html:

> While the startup file would typically be mostly used for various type of configuration, there’s no restriction to what you can do in it - you have access to the entire Howl API.

You've just told me this isn't true, so it should probably be updated. That might also tie into my FAQ issue #339.

**Comment by shalabhc** [comment] 2017-03-26 04:17
Hmm, I wonder if we should execute init.moon *after* app-ready?

**Comment by nilnor** [comment] 2017-03-27 08:28
I'm thinking that evaluating the init files after we're loaded might have the unfortunate effect of causing some flickering, as themes, etc. are reloaded after we're loaded. A quick test doesn't show any problems with it though, so it's something that could be looked at further.
