### ISSUE TITLE
bug: when using block cursor, selection rectangle under the cursor is not visible

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#462] opened 2018-08-15 15:00 UTC
When block cursor is enabled, character under cursor is not drawn as selected even though it is.

Cursor visible:
![howl-selection-cursor-visible](https://user-images.githubusercontent.com/411502/44155083-d50a6a30-a09b-11e8-9dbb-a322ec11b39c.png)

Cursor invisible:
![howl-selection-cursor-invisible](https://user-images.githubusercontent.com/411502/44155054-c8dd883c-a09b-11e8-934a-685d5775bb91.png)

Although 'e' is not marked as such, it is selected. This confuses user, like me.

EDIT:
This seem to be **off by one** error in selection engine related to #463

**Comment by kirbyfan64** [comment] 2018-08-15 16:25
Is this in the stable release or master branch? IIRC there was a bug fix a while ago related to an off-by-one error in highlights.

**Comment by etosan** [comment] 2018-09-04 11:27
Thanks I will pull my howl instance a new - maybe I broke it somehow.

**Comment by nilnor** [comment] 2018-09-05 02:33
I'm closing this as a duplicate of #463, since both of these issue relate to the same thing as I see it.

**Closed by nilnor** 2018-09-05 02:33 UTC
