### ISSUE TITLE
Out-of-bounds error when opening binary files

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#38] opened 2015-01-15 22:08 UTC
If I open [this file](https://www.dropbox.com/s/x9r15v9yo56cgpa/Hello.doc?dl=0) in Howl and navigate to the end of the file, this appears:

```
[string "../lib/howl/buffer_lines.moon"]:168: Character offset '6' out of bounds (length = 4)
```

**Comment by nilnor** [comment] 2015-01-16 19:15
Thanks for reporting, and for including a good test case! This is fixed in master now.

**Comment by nilnor** [comment] 2015-01-29 19:48
Sorry, but I had to revert the fix since it causes similar issues in more main-stream scenarios. The problem is with the difference in UTF-8 handling between Scintilla and glib. This will eventually solve itself when Scintilla is replaced (still some time off I'm afraid).

**Comment by kirbyfan64** [comment] 2015-01-29 22:41
Ok. I had noticed something weird went on opening one of my C++ files where Howl was complaining about bounds stuff. It's now resolved.

I doubt opening binary files in a text editor is necessarily common, anyway!

Out of curiosity, wouldn't it be possible to just use gtksourceview?

**Comment by nilnor** [comment] 2015-01-30 10:27
Yes, opening binary files is currently not that usable anyway, sometime in the future this might be handled better by providing a hex view used for binary files.

I did look at gtksourceview in the (very) early days and even used it for a short time in the beginning. It's nice, but I found it rather limited in the end and switched back to Scintilla. I'm currently working on a new, custom, editing engine that should make its debut in 0.4, so that will be the way forward.

**Comment by shalabhc** [comment] 2016-06-22 19:00
Is this now fixed since we are on Aullar?

**Comment by kirbyfan64** [comment] 2016-10-03 16:18
@shalabhc Not really. Upon opening the file, this pops up in the terminal:

```
(howl:5779): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
```

Not really too much of an issue. More interesting is navigating using the arrow keys: if I keep on hitting the right arrow, the following occurs:

- After going past the second "invalid character" box, the next tap of the arrow will skip the next three characters.
- Tapping the right arrow again will go backwards/left one character.
- One more tap will go right again.
- Another tap will go to the end of the file, with the error message "Illegal column 6".

**Comment by bugabinga** [comment] 2018-08-30 18:08
I think this can be closed now.
Tested the file with the master branch and there is neither error nor warning.

It is true, that the cursor seems to disappear when navigating to "invalid" characters.
But no action I have tried (move, type, copy, paste, delete) caused any error message.

**Comment by nilnor** [comment] 2018-09-04 12:01
Thanks @bugabinga, good catch! I did some work earlier this summer with ensuring that we always have valid UTF-8 in any buffer (this is some GLib routines require this, and in the case of GRexex will actually segfault in some scenarios). That I'm sure can lead to some other issues or requests, but this one we can now close :)

**Closed by nilnor** 2018-09-04 12:01 UTC
Labels: bug
